spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://10.4.74.189:5432/calculadora}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin123}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
